FROM --platform=linux/arm64 python:3.13

WORKDIR /application

COPY requirements.txt /application
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /application/app

ENTRYPOINT ["fastapi", "run", "app/main.py", "--port", "80"]
CMD []

EXPOSE 80
